
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Dec 08 05:20:31 CET 2024
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EXIT = 3;
  public static final int SEMICOLON = 5;
  public static final int PLUS = 6;
  public static final int IN = 10;
  public static final int APPLY = 13;
  public static final int COMM = 16;
  public static final int INTCONST = 21;
  public static final int OPENSQUARE = 11;
  public static final int TRUE = 14;
  public static final int COLON = 17;
  public static final int ID = 19;
  public static final int COMMA = 18;
  public static final int EOF = 0;
  public static final int MAIN = 2;
  public static final int FALSE = 15;
  public static final int MINUS = 7;
  public static final int CONST = 8;
  public static final int error = 1;
  public static final int ASSIGN = 4;
  public static final int FLOATCONST = 22;
  public static final int FOR = 9;
  public static final int BOOLCONST = 20;
  public static final int CLOSEDSQUARE = 12;
}

