
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Dec 04 07:31:30 CET 2023
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EXIT = 3;
  public static final int SEMICOLON = 9;
  public static final int PLUS = 10;
  public static final int INT = 5;
  public static final int IN = 14;
  public static final int COMM = 20;
  public static final int APPLY = 17;
  public static final int TRUE = 18;
  public static final int OPENSQUARE = 15;
  public static final int COLON = 21;
  public static final int ID = 4;
  public static final int COMMA = 22;
  public static final int FLOAT = 6;
  public static final int EOF = 0;
  public static final int MAIN = 2;
  public static final int FALSE = 19;
  public static final int MINUS = 11;
  public static final int CONST = 12;
  public static final int error = 1;
  public static final int ASSIGN = 8;
  public static final int BOOL = 7;
  public static final int FOR = 13;
  public static final int CLOSEDSQUARE = 16;
}

